/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DadaReseauxArtistRouteImport } from './routes/dada-reseaux-artist'
import { Route as CoursActivitesRouteImport } from './routes/cours-activites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtistRouteImport } from './routes/artist'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistIndexRouteImport } from './routes/artist.index'
import { Route as ArtistMusicRouteImport } from './routes/artist.music'
import { Route as ArtistEditRouteImport } from './routes/artist.edit'
import { Route as ArtistDiscographyRouteImport } from './routes/artist.discography'
import { Route as ArtistAlbumAlbumIdRouteImport } from './routes/artist.album.$albumId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DadaReseauxArtistRoute = DadaReseauxArtistRouteImport.update({
  id: '/dada-reseaux-artist',
  path: '/dada-reseaux-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursActivitesRoute = CoursActivitesRouteImport.update({
  id: '/cours-activites',
  path: '/cours-activites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistRoute = ArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistMusicRoute = ArtistMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistEditRoute = ArtistEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistDiscographyRoute = ArtistDiscographyRouteImport.update({
  id: '/discography',
  path: '/discography',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistAlbumAlbumIdRoute = ArtistAlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => ArtistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/artist': typeof ArtistRouteWithChildren
  '/contact': typeof ContactRoute
  '/cours-activites': typeof CoursActivitesRoute
  '/dada-reseaux-artist': typeof DadaReseauxArtistRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/artist/discography': typeof ArtistDiscographyRoute
  '/artist/edit': typeof ArtistEditRoute
  '/artist/music': typeof ArtistMusicRoute
  '/artist/': typeof ArtistIndexRoute
  '/artist/album/$albumId': typeof ArtistAlbumAlbumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/cours-activites': typeof CoursActivitesRoute
  '/dada-reseaux-artist': typeof DadaReseauxArtistRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/artist/discography': typeof ArtistDiscographyRoute
  '/artist/edit': typeof ArtistEditRoute
  '/artist/music': typeof ArtistMusicRoute
  '/artist': typeof ArtistIndexRoute
  '/artist/album/$albumId': typeof ArtistAlbumAlbumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/artist': typeof ArtistRouteWithChildren
  '/contact': typeof ContactRoute
  '/cours-activites': typeof CoursActivitesRoute
  '/dada-reseaux-artist': typeof DadaReseauxArtistRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/artist/discography': typeof ArtistDiscographyRoute
  '/artist/edit': typeof ArtistEditRoute
  '/artist/music': typeof ArtistMusicRoute
  '/artist/': typeof ArtistIndexRoute
  '/artist/album/$albumId': typeof ArtistAlbumAlbumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/artist'
    | '/contact'
    | '/cours-activites'
    | '/dada-reseaux-artist'
    | '/sign-in'
    | '/sign-up'
    | '/artist/discography'
    | '/artist/edit'
    | '/artist/music'
    | '/artist/'
    | '/artist/album/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/cours-activites'
    | '/dada-reseaux-artist'
    | '/sign-in'
    | '/sign-up'
    | '/artist/discography'
    | '/artist/edit'
    | '/artist/music'
    | '/artist'
    | '/artist/album/$albumId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/artist'
    | '/contact'
    | '/cours-activites'
    | '/dada-reseaux-artist'
    | '/sign-in'
    | '/sign-up'
    | '/artist/discography'
    | '/artist/edit'
    | '/artist/music'
    | '/artist/'
    | '/artist/album/$albumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ArtistRoute: typeof ArtistRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursActivitesRoute: typeof CoursActivitesRoute
  DadaReseauxArtistRoute: typeof DadaReseauxArtistRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dada-reseaux-artist': {
      id: '/dada-reseaux-artist'
      path: '/dada-reseaux-artist'
      fullPath: '/dada-reseaux-artist'
      preLoaderRoute: typeof DadaReseauxArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours-activites': {
      id: '/cours-activites'
      path: '/cours-activites'
      fullPath: '/cours-activites'
      preLoaderRoute: typeof CoursActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/': {
      id: '/artist/'
      path: '/'
      fullPath: '/artist/'
      preLoaderRoute: typeof ArtistIndexRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/music': {
      id: '/artist/music'
      path: '/music'
      fullPath: '/artist/music'
      preLoaderRoute: typeof ArtistMusicRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/edit': {
      id: '/artist/edit'
      path: '/edit'
      fullPath: '/artist/edit'
      preLoaderRoute: typeof ArtistEditRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/discography': {
      id: '/artist/discography'
      path: '/discography'
      fullPath: '/artist/discography'
      preLoaderRoute: typeof ArtistDiscographyRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/album/$albumId': {
      id: '/artist/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/artist/album/$albumId'
      preLoaderRoute: typeof ArtistAlbumAlbumIdRouteImport
      parentRoute: typeof ArtistRoute
    }
  }
}

interface ArtistRouteChildren {
  ArtistDiscographyRoute: typeof ArtistDiscographyRoute
  ArtistEditRoute: typeof ArtistEditRoute
  ArtistMusicRoute: typeof ArtistMusicRoute
  ArtistIndexRoute: typeof ArtistIndexRoute
  ArtistAlbumAlbumIdRoute: typeof ArtistAlbumAlbumIdRoute
}

const ArtistRouteChildren: ArtistRouteChildren = {
  ArtistDiscographyRoute: ArtistDiscographyRoute,
  ArtistEditRoute: ArtistEditRoute,
  ArtistMusicRoute: ArtistMusicRoute,
  ArtistIndexRoute: ArtistIndexRoute,
  ArtistAlbumAlbumIdRoute: ArtistAlbumAlbumIdRoute,
}

const ArtistRouteWithChildren =
  ArtistRoute._addFileChildren(ArtistRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ArtistRoute: ArtistRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursActivitesRoute: CoursActivitesRoute,
  DadaReseauxArtistRoute: DadaReseauxArtistRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
