/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArtistRouteImport } from './routes/artist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistIndexRouteImport } from './routes/artist.index'
import { Route as ArtistMusicRouteImport } from './routes/artist.music'
import { Route as ArtistEditRouteImport } from './routes/artist.edit'
import { Route as ArtistDiscographyRouteImport } from './routes/artist.discography'
import { Route as ArtistAlbumAlbumIdRouteImport } from './routes/artist.album.$albumId'

const ArtistRoute = ArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistMusicRoute = ArtistMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistEditRoute = ArtistEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistDiscographyRoute = ArtistDiscographyRouteImport.update({
  id: '/discography',
  path: '/discography',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistAlbumAlbumIdRoute = ArtistAlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => ArtistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRouteWithChildren
  '/artist/discography': typeof ArtistDiscographyRoute
  '/artist/edit': typeof ArtistEditRoute
  '/artist/music': typeof ArtistMusicRoute
  '/artist/': typeof ArtistIndexRoute
  '/artist/album/$albumId': typeof ArtistAlbumAlbumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artist/discography': typeof ArtistDiscographyRoute
  '/artist/edit': typeof ArtistEditRoute
  '/artist/music': typeof ArtistMusicRoute
  '/artist': typeof ArtistIndexRoute
  '/artist/album/$albumId': typeof ArtistAlbumAlbumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artist': typeof ArtistRouteWithChildren
  '/artist/discography': typeof ArtistDiscographyRoute
  '/artist/edit': typeof ArtistEditRoute
  '/artist/music': typeof ArtistMusicRoute
  '/artist/': typeof ArtistIndexRoute
  '/artist/album/$albumId': typeof ArtistAlbumAlbumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artist'
    | '/artist/discography'
    | '/artist/edit'
    | '/artist/music'
    | '/artist/'
    | '/artist/album/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artist/discography'
    | '/artist/edit'
    | '/artist/music'
    | '/artist'
    | '/artist/album/$albumId'
  id:
    | '__root__'
    | '/'
    | '/artist'
    | '/artist/discography'
    | '/artist/edit'
    | '/artist/music'
    | '/artist/'
    | '/artist/album/$albumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistRoute: typeof ArtistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/': {
      id: '/artist/'
      path: '/'
      fullPath: '/artist/'
      preLoaderRoute: typeof ArtistIndexRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/music': {
      id: '/artist/music'
      path: '/music'
      fullPath: '/artist/music'
      preLoaderRoute: typeof ArtistMusicRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/edit': {
      id: '/artist/edit'
      path: '/edit'
      fullPath: '/artist/edit'
      preLoaderRoute: typeof ArtistEditRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/discography': {
      id: '/artist/discography'
      path: '/discography'
      fullPath: '/artist/discography'
      preLoaderRoute: typeof ArtistDiscographyRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/album/$albumId': {
      id: '/artist/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/artist/album/$albumId'
      preLoaderRoute: typeof ArtistAlbumAlbumIdRouteImport
      parentRoute: typeof ArtistRoute
    }
  }
}

interface ArtistRouteChildren {
  ArtistDiscographyRoute: typeof ArtistDiscographyRoute
  ArtistEditRoute: typeof ArtistEditRoute
  ArtistMusicRoute: typeof ArtistMusicRoute
  ArtistIndexRoute: typeof ArtistIndexRoute
  ArtistAlbumAlbumIdRoute: typeof ArtistAlbumAlbumIdRoute
}

const ArtistRouteChildren: ArtistRouteChildren = {
  ArtistDiscographyRoute: ArtistDiscographyRoute,
  ArtistEditRoute: ArtistEditRoute,
  ArtistMusicRoute: ArtistMusicRoute,
  ArtistIndexRoute: ArtistIndexRoute,
  ArtistAlbumAlbumIdRoute: ArtistAlbumAlbumIdRoute,
}

const ArtistRouteWithChildren =
  ArtistRoute._addFileChildren(ArtistRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistRoute: ArtistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
